#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 102

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 41

#define SERIAL_NUMBER "ODyMq/3v4wxq"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

